### PR TITLE
Update Cryptographic-functions.md

### PR DESCRIPTION
**Pull request by toine08**
typo error at line 30

### CODE REVIEW

**Review by DevABDee — COMMENTED** [review]
LGTM!

**Comment by toine08** [comment]
Line 30 you wrote k`eccack256()` and it should be `keccack256()`right ? it was what I meant with typo error!

**Comment by DevABDee** [comment]
@toine08 yes you are right. Thats why I said LGTM (Looks good to me :))

**Comment by toine08** [comment]
oh sorry I misunderstood so my bad !:)

**Review by CJ42 — APPROVED** [review]

**Comment by CJ42** [comment]
Thank you @DevABDee !

**Pull request merged**
